- task: Maven@3
  inputs:
    mavenPomFile: 'springboot/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/*jar'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false