- task: Maven@3
  inputs:
    mavenPomFile: 'spring-boot-hello/pom.xml'
    goals: 'install'
    publishJUnitResults: true
    testResultsFiles: '**/target/*.jar'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'